/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDodoWebhookRouteImport } from './routes/api/public/dodo-webhook'
import { Route as ApiPublicLicenseActivateRouteImport } from './routes/api/public/license/activate'
import { Route as ApiPublicLicenseVerifyRouteImport } from './routes/api/public/license/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDodoWebhookRoute = ApiPublicDodoWebhookRouteImport.update({
  id: '/api/public/dodo-webhook',
  path: '/api/public/dodo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseActivateRoute =
  ApiPublicLicenseActivateRouteImport.update({
    id: '/api/public/license/activate',
    path: '/api/public/license/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseVerifyRoute = ApiPublicLicenseVerifyRouteImport.update({
  id: '/api/public/license/verify',
  path: '/api/public/license/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/dodo-webhook'
    | '/api/public/license/activate'
    | '/api/public/license/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/dodo-webhook'
    | '/api/public/license/activate'
    | '/api/public/license/verify'
  id:
    | '__root__'
    | '/'
    | '/api/public/dodo-webhook'
    | '/api/public/license/activate'
    | '/api/public/license/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDodoWebhookRoute: typeof ApiPublicDodoWebhookRoute
  ApiPublicLicenseActivateRoute: typeof ApiPublicLicenseActivateRoute
  ApiPublicLicenseVerifyRoute: typeof ApiPublicLicenseVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dodo-webhook': {
      id: '/api/public/dodo-webhook'
      path: '/api/public/dodo-webhook'
      fullPath: '/api/public/dodo-webhook'
      preLoaderRoute: typeof ApiPublicDodoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/activate': {
      id: '/api/public/license/activate'
      path: '/api/public/license/activate'
      fullPath: '/api/public/license/activate'
      preLoaderRoute: typeof ApiPublicLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/verify': {
      id: '/api/public/license/verify'
      path: '/api/public/license/verify'
      fullPath: '/api/public/license/verify'
      preLoaderRoute: typeof ApiPublicLicenseVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDodoWebhookRoute: ApiPublicDodoWebhookRoute,
  ApiPublicLicenseActivateRoute: ApiPublicLicenseActivateRoute,
  ApiPublicLicenseVerifyRoute: ApiPublicLicenseVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
