/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as CompareSlugRouteImport } from './routes/compare/$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as ApiPublicDodoWebhookRouteImport } from './routes/api/public/dodo-webhook'
import { Route as AppsInsectscanIndexRouteImport } from './routes/apps/insectscan/index'
import { Route as AppsInsectscanPrivacyRouteImport } from './routes/apps/insectscan/privacy'
import { Route as AppsInsectscanSupportRouteImport } from './routes/apps/insectscan/support'
import { Route as AppsInsectscanTermsRouteImport } from './routes/apps/insectscan/terms'
import { Route as ApiPublicLicenseActivateRouteImport } from './routes/api/public/license/activate'
import { Route as ApiPublicLicenseDeactivateRouteImport } from './routes/api/public/license/deactivate'
import { Route as ApiPublicLicenseVerifyRouteImport } from './routes/api/public/license/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDodoWebhookRoute = ApiPublicDodoWebhookRouteImport.update({
  id: '/api/public/dodo-webhook',
  path: '/api/public/dodo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsInsectscanIndexRoute = AppsInsectscanIndexRouteImport.update({
  id: '/apps/insectscan/',
  path: '/apps/insectscan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsInsectscanPrivacyRoute = AppsInsectscanPrivacyRouteImport.update({
  id: '/apps/insectscan/privacy',
  path: '/apps/insectscan/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsInsectscanSupportRoute = AppsInsectscanSupportRouteImport.update({
  id: '/apps/insectscan/support',
  path: '/apps/insectscan/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsInsectscanTermsRoute = AppsInsectscanTermsRouteImport.update({
  id: '/apps/insectscan/terms',
  path: '/apps/insectscan/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseActivateRoute =
  ApiPublicLicenseActivateRouteImport.update({
    id: '/api/public/license/activate',
    path: '/api/public/license/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseDeactivateRoute =
  ApiPublicLicenseDeactivateRouteImport.update({
    id: '/api/public/license/deactivate',
    path: '/api/public/license/deactivate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseVerifyRoute = ApiPublicLicenseVerifyRouteImport.update({
  id: '/api/public/license/verify',
  path: '/api/public/license/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/apps/insectscan/privacy': typeof AppsInsectscanPrivacyRoute
  '/apps/insectscan/support': typeof AppsInsectscanSupportRoute
  '/apps/insectscan/terms': typeof AppsInsectscanTermsRoute
  '/apps/insectscan/': typeof AppsInsectscanIndexRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/apps/insectscan/privacy': typeof AppsInsectscanPrivacyRoute
  '/apps/insectscan/support': typeof AppsInsectscanSupportRoute
  '/apps/insectscan/terms': typeof AppsInsectscanTermsRoute
  '/apps/insectscan': typeof AppsInsectscanIndexRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/apps/insectscan/privacy': typeof AppsInsectscanPrivacyRoute
  '/apps/insectscan/support': typeof AppsInsectscanSupportRoute
  '/apps/insectscan/terms': typeof AppsInsectscanTermsRoute
  '/apps/insectscan/': typeof AppsInsectscanIndexRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/auth'
    | '/download'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/account'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/guides/'
    | '/api/public/dodo-webhook'
    | '/apps/insectscan/privacy'
    | '/apps/insectscan/support'
    | '/apps/insectscan/terms'
    | '/apps/insectscan/'
    | '/api/public/license/activate'
    | '/api/public/license/deactivate'
    | '/api/public/license/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/auth'
    | '/download'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/account'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/guides'
    | '/api/public/dodo-webhook'
    | '/apps/insectscan/privacy'
    | '/apps/insectscan/support'
    | '/apps/insectscan/terms'
    | '/apps/insectscan'
    | '/api/public/license/activate'
    | '/api/public/license/deactivate'
    | '/api/public/license/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate'
    | '/auth'
    | '/download'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/guides/'
    | '/api/public/dodo-webhook'
    | '/apps/insectscan/privacy'
    | '/apps/insectscan/support'
    | '/apps/insectscan/terms'
    | '/apps/insectscan/'
    | '/api/public/license/activate'
    | '/api/public/license/deactivate'
    | '/api/public/license/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CompareSlugRoute: typeof CompareSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ApiPublicDodoWebhookRoute: typeof ApiPublicDodoWebhookRoute
  AppsInsectscanPrivacyRoute: typeof AppsInsectscanPrivacyRoute
  AppsInsectscanSupportRoute: typeof AppsInsectscanSupportRoute
  AppsInsectscanTermsRoute: typeof AppsInsectscanTermsRoute
  AppsInsectscanIndexRoute: typeof AppsInsectscanIndexRoute
  ApiPublicLicenseActivateRoute: typeof ApiPublicLicenseActivateRoute
  ApiPublicLicenseDeactivateRoute: typeof ApiPublicLicenseDeactivateRoute
  ApiPublicLicenseVerifyRoute: typeof ApiPublicLicenseVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dodo-webhook': {
      id: '/api/public/dodo-webhook'
      path: '/api/public/dodo-webhook'
      fullPath: '/api/public/dodo-webhook'
      preLoaderRoute: typeof ApiPublicDodoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/insectscan/': {
      id: '/apps/insectscan/'
      path: '/apps/insectscan'
      fullPath: '/apps/insectscan/'
      preLoaderRoute: typeof AppsInsectscanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/insectscan/privacy': {
      id: '/apps/insectscan/privacy'
      path: '/apps/insectscan/privacy'
      fullPath: '/apps/insectscan/privacy'
      preLoaderRoute: typeof AppsInsectscanPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/insectscan/support': {
      id: '/apps/insectscan/support'
      path: '/apps/insectscan/support'
      fullPath: '/apps/insectscan/support'
      preLoaderRoute: typeof AppsInsectscanSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/insectscan/terms': {
      id: '/apps/insectscan/terms'
      path: '/apps/insectscan/terms'
      fullPath: '/apps/insectscan/terms'
      preLoaderRoute: typeof AppsInsectscanTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/activate': {
      id: '/api/public/license/activate'
      path: '/api/public/license/activate'
      fullPath: '/api/public/license/activate'
      preLoaderRoute: typeof ApiPublicLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/deactivate': {
      id: '/api/public/license/deactivate'
      path: '/api/public/license/deactivate'
      fullPath: '/api/public/license/deactivate'
      preLoaderRoute: typeof ApiPublicLicenseDeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/verify': {
      id: '/api/public/license/verify'
      path: '/api/public/license/verify'
      fullPath: '/api/public/license/verify'
      preLoaderRoute: typeof ApiPublicLicenseVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivateRoute: ActivateRoute,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CompareSlugRoute: CompareSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ApiPublicDodoWebhookRoute: ApiPublicDodoWebhookRoute,
  AppsInsectscanPrivacyRoute: AppsInsectscanPrivacyRoute,
  AppsInsectscanSupportRoute: AppsInsectscanSupportRoute,
  AppsInsectscanTermsRoute: AppsInsectscanTermsRoute,
  AppsInsectscanIndexRoute: AppsInsectscanIndexRoute,
  ApiPublicLicenseActivateRoute: ApiPublicLicenseActivateRoute,
  ApiPublicLicenseDeactivateRoute: ApiPublicLicenseDeactivateRoute,
  ApiPublicLicenseVerifyRoute: ApiPublicLicenseVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
