/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicDodoWebhookRouteImport } from './routes/api/public/dodo-webhook'
import { Route as ApiPublicLicenseActivateRouteImport } from './routes/api/public/license/activate'
import { Route as ApiPublicLicenseDeactivateRouteImport } from './routes/api/public/license/deactivate'
import { Route as ApiPublicLicenseVerifyRouteImport } from './routes/api/public/license/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDodoWebhookRoute = ApiPublicDodoWebhookRouteImport.update({
  id: '/api/public/dodo-webhook',
  path: '/api/public/dodo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseActivateRoute =
  ApiPublicLicenseActivateRouteImport.update({
    id: '/api/public/license/activate',
    path: '/api/public/license/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseDeactivateRoute =
  ApiPublicLicenseDeactivateRouteImport.update({
    id: '/api/public/license/deactivate',
    path: '/api/public/license/deactivate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseVerifyRoute = ApiPublicLicenseVerifyRouteImport.update({
  id: '/api/public/license/verify',
  path: '/api/public/license/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/auth'
    | '/download'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/account'
    | '/api/public/dodo-webhook'
    | '/api/public/license/activate'
    | '/api/public/license/deactivate'
    | '/api/public/license/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/auth'
    | '/download'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/account'
    | '/api/public/dodo-webhook'
    | '/api/public/license/activate'
    | '/api/public/license/deactivate'
    | '/api/public/license/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate'
    | '/auth'
    | '/download'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/api/public/dodo-webhook'
    | '/api/public/license/activate'
    | '/api/public/license/deactivate'
    | '/api/public/license/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicDodoWebhookRoute: typeof ApiPublicDodoWebhookRoute
  ApiPublicLicenseActivateRoute: typeof ApiPublicLicenseActivateRoute
  ApiPublicLicenseDeactivateRoute: typeof ApiPublicLicenseDeactivateRoute
  ApiPublicLicenseVerifyRoute: typeof ApiPublicLicenseVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/dodo-webhook': {
      id: '/api/public/dodo-webhook'
      path: '/api/public/dodo-webhook'
      fullPath: '/api/public/dodo-webhook'
      preLoaderRoute: typeof ApiPublicDodoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/activate': {
      id: '/api/public/license/activate'
      path: '/api/public/license/activate'
      fullPath: '/api/public/license/activate'
      preLoaderRoute: typeof ApiPublicLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/deactivate': {
      id: '/api/public/license/deactivate'
      path: '/api/public/license/deactivate'
      fullPath: '/api/public/license/deactivate'
      preLoaderRoute: typeof ApiPublicLicenseDeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/verify': {
      id: '/api/public/license/verify'
      path: '/api/public/license/verify'
      fullPath: '/api/public/license/verify'
      preLoaderRoute: typeof ApiPublicLicenseVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivateRoute: ActivateRoute,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicDodoWebhookRoute: ApiPublicDodoWebhookRoute,
  ApiPublicLicenseActivateRoute: ApiPublicLicenseActivateRoute,
  ApiPublicLicenseDeactivateRoute: ApiPublicLicenseDeactivateRoute,
  ApiPublicLicenseVerifyRoute: ApiPublicLicenseVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
